### ISSUE TITLE
potential IGSDB formats for response to buildingenvelopedata query for optical data

### ISSUE THREAD

**Issue by StephenCzarnecki** [ise621/building-envelope-data#186]
I tried to make a partial example of what the optical data for a clear glass layer from the igsdb would look like following the opticalData schema.  I am not sure I did it correctly and am attaching it here for potential feedback based on what I have so far.

However in doing so I noticed that the optical schema allows the data to be returned as a getHttpsResource instead.  And we are wondering if we could instead use urls for the existing igsdb.lbl.gov api instead of transforming the data.  I am attaching an example of the response to a query to the igsdb for the same clear glass record.  We hope you can take a look at it and see if it would be appropriate to use. 

If it is potentially appropriate to use the url instead then the question of whether the example transforming the data to the opticalData schema can be ignored.

IGSDB response (github required the file to end in .txt and would not accept json):  
[igsdb_nfrc_102.json.txt](https://github.com/ise621/building-envelope-data/files/5948041/igsdb_nfrc_102.json.txt)
  
IGSDB url used to generate the response:  https://igsdb.lbl.gov/api/v1/products/363/

Attempt at transforming optical data to conform to the opticalData.json schema:  
[buildingenvelopedata clear 3 optical data example.json.txt](https://github.com/ise621/building-envelope-data/files/5948048/buildingenvelopedata.clear.3.optical.data.example.json.txt)

**Comment by simon-wacker** [comment]
You need to differentiate between
1. the [GraphQL database API](https://github.com/ise621/building-envelope-data/blob/develop/apis/database.graphql) that is meant to be used by the metabase (what is also called IKDB) to communicate with databases;
2. the [JSON Schemas](https://github.com/ise621/building-envelope-data/tree/develop/schemas) that can be used to represent for example [optical data](https://github.com/ise621/building-envelope-data/blob/develop/schemas/opticalData.json) in a standardized way.

The GraphQL API returns meta information about data (like name, description, the method by which it was measured or simulated, and so forth) and a URL to an HTTP(S) resource together with meta information about that resource (like in which format the data behind that resource is formatted, in particular, a media type). The result of `GET`-requesting such a resource *could* be JSON with measurement data that matches one of the JSON schemas; but it *could* also be a XML with BSDF data that matches some BSDF XML schema and anything else (the only requirement for data behind such a resource is that it is in a well-documented format). The metabase (or IKDB) will only look at the meta information and never touch whatever lies behind those resources (which could potentially be Gigabytes of data).

The JSON schemas *try* to define data in the most general fashion to make it possible to store novel measurement and simulation data for which there is _no_ standard way yet. However, we don't mean them to be used for data for which there already is a community standard like BSDF XML. That you have been able to convert IGSDB data to the optical data JSON schema means at least that it is general enough for the IGSDB data. If you still want feedback on whether the conversion is correct, @christoph-maurer may have a look.

**Comment by StephenCzarnecki** [comment]
@simon-wacker Thank you for your clarification.  Based on that at this time we do not believe there is any need for @christoph-maurer to review the example above.  Instead we will create another example in the next day or two based on our new understanding and ask questions about that instead.

**Comment by StephenCzarnecki** [comment]
@simon-wacker Based on your previous response I tried to put together another example that might be a response from igsdb.lbl.gov to the query described in https://github.com/ise621/building-envelope-data/blob/develop/apis/database.graphql
With the assumption that the query is for “opticalData” instead of “data” so that “nearnormalHemisphericalVisibleTransmittances” is included.  Essentially the “OpticalData” type as described in https://github.com/ise621/building-envelope-data/blob/develop/apis/database.graphql

Assuming that the id value corresponds to the record that is returned.  The first question is does this represent all of the metadata that the ICON metabase would ask the IGSDB database for?  If not then again disregard the following.

The following example is actually yaml not json in order to get comments and formatting.  Hopefully it is clear enough.  The comments are used for questions or clarifications.  But before getting into individual questions the larger issue is if this seems to represent a result that the ICON metabase would expect when querying the IGSDB.

```yaml
{
  "data": {
    "uuid": "363", #Clarification:  Currently the IGSDB does not use UUIDs for records.  This may change.  However this ID + timestamp would uniquly idenfity a record"
    "timestamp": "2001-10-02T15:54:55-04:00",  #Question: If this record has never been updated then the timestamp is the same as createdAt correct?"
    "componentId": "810e84b4-9ebf-416c-88ea-aade848f1fdf", #Clarification:  The ID of the product as issued by the ICON metabase.
    "name": "Generic Clear Glass",
    "description": null,
    "warnings": [],
    "creatorId": "34cdaad1-1383-4122-8f0d-837fe5346cfe", #Clarification/Question:  This is a placeholder UUID, the real one would be the UUID for LBNL stored in the ICON metabase correct?"
    "createdAt": "2001-10-02T15:54:55-04:00",
    "appliedMethod": {
      "methodId": "8227f9a2-722c-4fd5-a512-ebfac56c629d", #Question:  This UUID corresponds to a method stored in the ICON metabase correct?  But we are not sure quite what method means in this case since there are several 'methods' used to create data in IGSDB.  e.g. different ways of measuring and different parts of different standards used to create calculated results."
      "arguments": "[]", #Depending on what 'AppliedMethod' means in this case there may or may not be arguments"
      "sources": "[]", #Depending on what 'AppliedMethod' means in this case there may or may not be sources"
    },
    "approvals": "I am temporarily leaving out approvals in order to try to resolve other questions first",
    "resources": [
      {
        "description": "IGSDB glazing data", #Clarification/Question:  Or something else that describes this as not a shading layer and not bsdf.  Is something like that an appropriate description?"
        "hashValue": "bca45733b010c3b0b8f940dd7f878ce9a679210d449768fa4dd55692684b64db", #Clarification:  This is the sha-256 of the body of the response from running a GET request on the locator url"
        "locator": "https://igsdb.lbl.gov/api/v1/products/363/", #Clarification/Question:  Based on previous response it is OK to use a url for the existing REST interface so long as the format is documented via a link that can be found using the formatID uuid to query the ICON metabase correct?
        "formatId": "ff78b7d3-f405-48a2-9f19-ab83f948c5d0", #Clarification/Question: This is a uuid which corresponds to a format in the metabase (ICON).  Can that format in the metabase be something with a name like “IGSDB json” and has that has a reference to https://igsdb.lbl.gov/openapi/ or potentially some other url in igsdb.lbl.gov that documents the data structure?"
        "archivedFilesMetaInformation": [],
      }
    ],
    "resourceTree": null, #Question:  This seems to be marked as required but I do not know if IGSDB has this.  The spec says 'Note that all resources describe the same data only in different formats.' but I think the IGSDB just has a single format for each record.  e.g. The this 'Generic Clear Glass' record only has specular wavelength values.  It does not also have dual-band BSDF matrices under a different resource."
    "approval": "Again temporarily omitting approvals to resolve other issues first",
    "locale": "en-US",
    "nearnormalHemisphericalVisibleTransmittances": [0.89926]
      #Question 1: What does 'mirrored' mean in 'Mirrored nearnormal hemispherical visible transmittance values'?
      #Question 2: Is this the only numeric value that the metabase (ICON) will be querying on and expecting for optical data?  The IGSDB has many other values such as thickness, visible reflectance, solar transmittance, etc...  Are those not used by the ICON metabase?
  }
}
```
