### ISSUE TITLE
Mirror more values to facilitate the search

### ISSUE THREAD

**Issue by christoph-maurer** [ise621/building-envelope-data#233]
In addition to `nearnormalHemisphericalVisibleTransmittances`, `gValues` and `uValues`, we believe it would be good to mirror as well `nearnormalHemisphericalVisibleReflectances`, `nearnormalHemisphericalSolarTransmittances`, `nearnormalHemisphericalSolarReflectance`, `infraredEmittance`, the colour rendering index `CRI` and the CIELAB colour parameters `L*`, `a*`, `b*`.

@StephenCzarnecki Would this be possible after the implementation of the new JSON format?

**Comment by christoph-maurer** [comment]
In order to illustrate how the new values to be mirrored look like according to the JSON Schema, I have created examples:

- [nearnormalHemisphericalVisibleReflectances](https://github.com/ise621/building-envelope-data/blob/develop/tests/valid/opticalData/mirroredValues/nearnormalHemisphericalVisibleReflectance.json)
- [nearnormalHemisphericalSolarTransmittances](https://github.com/ise621/building-envelope-data/blob/develop/tests/valid/opticalData/mirroredValues/nearnormalHemisphericalSolarTransmittance.json)
- [nearnormalHemisphericalSolarReflectance](https://github.com/ise621/building-envelope-data/blob/develop/tests/valid/opticalData/mirroredValues/nearnormalHemisphericalSolarReflectance.json)
- [infraredEmittance](https://github.com/ise621/building-envelope-data/blob/develop/tests/valid/opticalData/mirroredValues/infraredEmittance.json)
- [CRI and L*, a*, b*](https://github.com/ise621/building-envelope-data/blob/develop/examples/dbe/optical/ColourRenderingIndexCIELAB.json)

**Comment by StephenCzarnecki** [comment]
@christoph-maurer I'm not sure I understand exactly what you are requesting here.  Here are some thoughts based on what I currently understand, please correct me where I am mistaken.

From what I understood before the "mirrored" values are those values that can be returned by the GraphQL metadata query.  And so far at least those values do not really have anything to do with the ICON JSON schemas.  

Using ```nearnormalHemisphericalVisibleTransmittances``` as an example:

In the database.graphql file there is ```type OpticalData``` which has the following:

```yaml
  """
  Mirrored nearnormal hemispherical visible transmittance values that occur in
  the data
  """
  nearnormalHemisphericalVisibleTransmittances: [Float!]!
```

And there nearnormalHemisphericalVisibleTransmittances is just an array of floats.  It does not seem to have anything to do with the ICON JSON schemas.  Is that ```Float``` type going to be changed into something else, specifically a ```dataPoint``` from ```schemas/opticalData.json```?

Also is the intent to expand the ```OpticalData``` type in ```database.graphql``` to look like the following?

```yaml
  """
  Mirrored nearnormal hemispherical visible reflectance values that occur in
  the data
  """
  nearnormalHemisphericalVisibleReflectances: [Float!]!

  """
  Mirrored nearnormal hemispherical solar transmittance values that occur in
  the data
  """
  nearnormalHemisphericalSolarTransmittances: [Float!]!

  """
  Mirrored nearnormal hemispherical solar reflectance values that occur in
  the data
  """
  nearnormalHemisphericalSolarReflectances: [Float!]!

  """
  Mirrored infrared emittance values that occur in
  the data
  """
  infraredEmittances: [Float!]!

  """
  Mirrored CRI values that occur in
  the data
  """
  cri: [Float!]!

  """
  Mirrored Lab values that occur in
  the data
  """
  lab: [?!]! # Not sure what the type should be here, seems like either it should be a 3-tuple or some other defined type

```

If so then should the ```float``` values be something else?

Also if these values are being added to the mirrored data should they also be added to the list of things that can be queried for?  E.g. should ```OpticalDataPropositionInput``` be changed to look like this?

```yaml
input OpticalDataPropositionInput {
  componentId: UuidPropositionInput
  and: [OpticalDataPropositionInput!]
  nearnormalHemisphericalVisibleTransmittance: FloatPropositionInput
  nearnormalHemisphericalVisibleReflectances: FloatPropositionInput
  nearnormalHemisphericalSolarTransmittances: FloatPropositionInput
  nearnormalHemisphericalSolarReflectance: FloatPropositionInput
  infraredEmittance: FloatPropositionInput
  cri: FloatPropositionInput
  lab: NotYetDefinedPropositionInput
  not: OpticalDataPropositionInput
  or: [OpticalDataPropositionInput!]
}
```

Finally just a note:  I do not think the IGSDB has CRI.
