### ISSUE TITLE
Clarification for how client databases handle queries with filters for information they do not have

### ISSUE THREAD

**Issue by StephenCzarnecki** [ise621/building-envelope-data#239]
I just want to clarify how client databases handle metadata queries containing filters for information they do not have.  My reading of the database.graphql file suggests that the parts of the queries dealing with non-existent data evaluate to false but I want to make sure that is correct.

An example to clarify the question:

The IGSDB does not have U-values.  So it seems to me that the query to the IGSDB that has this for a where clause

```yaml
where: {
  gValue: { greaterThanOrEqualTo: 0.5 } 
  nearnormalHemisphericalVisibleTransmittance: {greaterThanOrEqualTo: 0.0, lessThanOrEqualTo: 1.0 }}
}
```

would return no results.  

This is because the gValue filter and nearnormalHemisphericalVisibleTransmittance filter are ANDed together and since no record in the IGSDB has a gValue >= 0.5 the gValue filter will always be false.  Therefore it does not matter what the rest of the query asks since anything ANDed with false is false. 

Is that correct?
