### ISSUE TITLE
DataPropositionInput - why is an empty "and" true and an empty "or" false?

### ISSUE THREAD

**Issue by StephenCzarnecki** [ise621/building-envelope-data#240]
In the database.graphql file in the ```DataPropositionInput``` section there are the following comments:

```yaml
  """
  True for data for which each proposition in `and` is true, otherwise false.
  In particular, it is true if there is no proposition in `and`.
  """
  and: [DataPropositionInput!]

#...

  """
  True for data for which at least one proposition in `or` is true, otherwise
  false. In particular, it is false if there is no proposition in `or`.
  """
  or: [DataPropositionInput!]
```

It seems to me that means that ```and:[]``` evaluates to true and ```or:[]``` evaluates to false.

For example:

If a query to the IGSDB has this where section

```yaml
where: {
  nearnormalHemisphericalVisibleTransmittance: {greaterThanOrEqualTo: 0.0, lessThanOrEqualTo: 1.0 }}
  and: []
}
```
then it would return almost all of the records in the IGSDB (there are some records that do not have visible transmittance)

However if the query instead had this where section:

```yaml
where: {
  nearnormalHemisphericalVisibleTransmittance: {greaterThanOrEqualTo: 0.0, lessThanOrEqualTo: 1.0 }}
  or: []
}
```

Then it would return no results.

If this is true can you clarify why this is?  And if this is not correct can you correct where I have gone wrong?
